apiVersion: 1
policies:
  - orgId: 1
    receiver: telegram
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: ntfy
        group_by: ['alertname']
        matchers:
          - severity=critical
        continue: true
