services:
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2-builder-alpine AS builder
        RUN xcaddy build --with github.com/caddy-dns/cloudflare
        FROM caddy:2-alpine
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    container_name: caddy
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${SSD_PATH}/caddy/data:/data
      - ${SSD_PATH}/caddy/config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - DOMAIN=${DOMAIN}
    mem_limit: 512m
    cpus: 1
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 10s
      retries: 3

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - CF_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${CLOUDFLARE_DOMAINS}
      - PROXIED=true
      - IP6_PROVIDER=none
      - UPDATE_CRON=@every 5m
    mem_limit: 64m
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "cloudflare.com"]
      interval: 300s
      timeout: 10s
      retries: 2

