# HashiCorp Vault - Secret Management Service
# 
# Purpose: Centralized secret storage and management
# Features: Encrypted storage, API access, secret rotation, audit logging
# Integration: Used by both GitHub Actions and homeserver services
# 
# Usage: docker-compose -f docker-compose.yml -f docker-compose.vault.yml up -d

services:
  # HashiCorp Vault - Secret Management Server
  vault:
    image: hashicorp/vault:1.15.4
    container_name: vault
    restart: unless-stopped
    networks:
      - backend
      - frontend  # For API access
    ports:
      - "8200:8200"
    volumes:
      - ./configs/vault:/vault/config:ro
      - ${SSD_PATH}/vault/data:/vault/data
      - ${SSD_PATH}/vault/logs:/vault/logs
      - ${SSD_PATH}/vault/policies:/vault/policies:ro
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"storage":{"file":{"path":"/vault/data"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}},"ui":true,"log_level":"INFO"}
    command: vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    mem_limit: 512m
    cpus: 1
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "homeserver.service=vault"
      - "homeserver.component=security"

  # Vault Agent - Secret synchronization for services
  vault-agent:
    image: hashicorp/vault:1.15.4
    container_name: vault-agent
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./configs/vault/agent:/vault/config:ro
      - ${SSD_PATH}/vault/agent:/vault/agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - VAULT_ADDR=http://vault:8200
    command: vault agent -config=/vault/config/agent.hcl
    depends_on:
      vault:
        condition: service_healthy
    mem_limit: 256m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    labels:
      - "homeserver.service=vault-agent"
      - "homeserver.component=security"

networks:
  vault-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
    labels:
      - "homeserver.network=vault"
      - "homeserver.component=security"