name: 'Detect Changes'
description: 'Detects file changes and maps them to service groups for deployment'

inputs:
  force-full:
    description: 'Force full deployment'
    required: false
    default: 'false'

outputs:
  core:
    description: 'Core infrastructure needs deployment'
    value: ${{ steps.changes.outputs.core }}
  application:
    description: 'Application services need deployment'
    value: ${{ steps.changes.outputs.application }}
  monitoring:
    description: 'Monitoring services need deployment'
    value: ${{ steps.changes.outputs.monitoring }}
  security:
    description: 'Security services need deployment'
    value: ${{ steps.changes.outputs.security }}
  infrastructure:
    description: 'Infrastructure services need deployment'
    value: ${{ steps.changes.outputs.infrastructure }}
  full_deploy:
    description: 'Full deployment needed'
    value: ${{ steps.changes.outputs.full_deploy }}
  changed_groups:
    description: 'JSON array of service groups that need deployment'
    value: ${{ steps.changes.outputs.changed_groups }}

runs:
  using: 'composite'
  steps:
    - name: Detect File Changes and Map to Service Groups
      id: changes
      shell: bash
      run: |
        set -e
        
        core="false"
        application="false"
        monitoring="false"
        security="false"
        infrastructure="false"
        full_deploy="false"
        
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.force-full }}" == "true" ]]; then
          echo "Manual full deployment requested"
          full_deploy="true"
        else
          echo "Detecting changed files..."
          
          # Always running on master branch - use GitHub's provided commit references
          PREVIOUS_COMMIT="${{ github.event.before }}"
          CURRENT_COMMIT="${{ github.sha }}"
          
          # Handle first commit case
          if [[ "$PREVIOUS_COMMIT" == "0000000000000000000000000000000000000000" ]]; then
            echo "First commit detected, triggering full deployment"
            full_deploy="true"
          else
            echo "Comparing commits: $PREVIOUS_COMMIT -> $CURRENT_COMMIT"
          fi
          
          # Only attempt diff if we haven't already decided on full deployment
          if [[ "$full_deploy" != "true" ]]; then
            # Configure git safe directory to avoid ownership issues in runner
            git config --global --add safe.directory "${{ github.workspace }}" 2>/dev/null || true
            
            # GitHub checkout with fetch-depth: 0 should provide all commits we need
            echo "Attempting git diff with provided commit references..."
            if git diff --name-only "$PREVIOUS_COMMIT" "$CURRENT_COMMIT" > changed_files.txt 2>/dev/null; then
              echo "Successfully detected file changes"
            else
              echo "Git diff failed - commits may not be available in checkout"
              echo "Debug: Previous commit exists: $(git cat-file -e "$PREVIOUS_COMMIT" 2>/dev/null && echo 'YES' || echo 'NO')"
              echo "Debug: Current commit exists: $(git cat-file -e "$CURRENT_COMMIT" 2>/dev/null && echo 'YES' || echo 'NO')"
              echo "Debug: Available commits: $(git log --oneline -5 | tr '\n' '; ')"
              echo "Triggering full deployment as fallback"
              full_deploy="true"
            fi
          else
            echo "Full deployment already triggered, skipping file change detection"
          fi
          
          if [[ "$full_deploy" == "true" ]]; then
            echo "Full deployment triggered, skipping file change analysis"
          fi
          
          if [[ "$full_deploy" != "true" ]]; then
            echo "Changed files:"
            cat changed_files.txt
            echo ""
            
            if grep -qE '^(docker-compose\.yml|scripts/|\.github/workflows/deploy\.yml)' changed_files.txt; then
              echo "Global files changed, triggering full deployment"
              full_deploy="true"
            else
              if grep -qE '^compose/core/' changed_files.txt; then
                core="true"
                echo "Core infrastructure changes detected"
              fi
              
              if grep -qE '^compose/(media|gaming)/' changed_files.txt; then
                application="true"
                echo "Application service changes detected"
              fi
              
              if grep -qE '^compose/monitoring/' changed_files.txt; then
                monitoring="true"
                echo "Monitoring service changes detected"
              fi
              
              if grep -qE '^compose/security/' changed_files.txt; then
                security="true"
                echo "Security service changes detected"
              fi
              
              if grep -qE '^compose/infrastructure/' changed_files.txt; then
                infrastructure="true"
                echo "Infrastructure service changes detected"
              fi
              
              if grep -qE '^configs/(caddy|mariadb|redis)/' changed_files.txt; then
                core="true"
                echo "Core configuration changes detected"
              fi
              
              if grep -qE '^configs/(prometheus|grafana|loki|alertmanager)/' changed_files.txt; then
                monitoring="true"
                echo "Monitoring configuration changes detected"
              fi
              
              if [[ "$application" == "true" || "$monitoring" == "true" || "$security" == "true" ]]; then
                core="true"
                echo "Auto-including core infrastructure due to service dependencies"
              fi
            fi
          fi
        fi
        
        echo "core=$core" >> $GITHUB_OUTPUT
        echo "application=$application" >> $GITHUB_OUTPUT
        echo "monitoring=$monitoring" >> $GITHUB_OUTPUT
        echo "security=$security" >> $GITHUB_OUTPUT
        echo "infrastructure=$infrastructure" >> $GITHUB_OUTPUT
        echo "full_deploy=$full_deploy" >> $GITHUB_OUTPUT
        
        # Generate JSON array of changed groups
        changed_groups_array=()
        if [[ "$full_deploy" == "true" ]]; then
          changed_groups_array=("infrastructure" "application" "monitoring" "security")
          # Core is always included when other groups change, so we add it separately
          changed_groups_array+=("core")
        else
          [[ "$core" == "true" ]] && changed_groups_array+=("core")
          [[ "$application" == "true" ]] && changed_groups_array+=("application")
          [[ "$monitoring" == "true" ]] && changed_groups_array+=("monitoring")
          [[ "$security" == "true" ]] && changed_groups_array+=("security")
          [[ "$infrastructure" == "true" ]] && changed_groups_array+=("infrastructure")
        fi
        
        # Convert to JSON array
        if [[ ${#changed_groups_array[@]} -eq 0 ]]; then
          changed_groups_json="[]"
        else
          changed_groups_json=$(printf '%s\n' "${changed_groups_array[@]}" | jq -R . | jq -s -c .)
        fi
        
        echo "changed_groups=$changed_groups_json" >> $GITHUB_OUTPUT
        
        if [[ -f changed_files.txt ]]; then
          echo "Uploading changed files list as artifact"
        fi
        
        echo ""
        echo "=== DEPLOYMENT DECISION SUMMARY ==="
        echo "Service group deployment decisions:"
        echo "  • Core ............. $core"
        echo "  • Application ...... $application"
        echo "  • Monitoring ....... $monitoring"
        echo "  • Security ......... $security"
        echo "  • Infrastructure ... $infrastructure"
        echo "  • Full deploy ...... $full_deploy"
        echo "  • Changed groups ... $changed_groups_json"
        echo "==================================="
