# Authelia Users Database
# 
# Purpose: Define users, groups, and authentication credentials
# Security: Passwords are hashed using Argon2id algorithm
# Management: Users can be added/removed by editing this file and restarting Authelia
#
# Password Generation:
# Use the authelia CLI to generate password hashes:
# docker run --rm authelia/authelia:latest authelia hash-password 'your_password'
#
# Groups:
# - admins: Full administrative access to all services
# - users: Standard user access to monitoring and media services
# - monitoring: Read-only access to monitoring systems

users:
  # Default admin user (change password and email)
  admin:
    displayname: "Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t1MF//X6yA"  # Change this!
    email: admin@homeserver.local
    groups:
      - admins
      - users

  # Monitoring service account for automated tasks
  monitoring:
    displayname: "Monitoring Service"
    password: "$argon2id$v=19$m=65536,t=3,p=4$c8/S3V3JSaD5Z9WD$RHOFcePSFrCwK12TG4RFgDaAaYzQHlxrGzK7A8xY5Ks"  # Change this!
    email: monitoring@homeserver.local
    groups:
      - monitoring

  # Example regular user (customize as needed)
  user1:
    displayname: "Home User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$8sKYVEG0i5lO5jX/$YIhEzWCl9E9D6Z1qG5Y3Y2Q2TbHvHzxJvY0jFc9Z2Lc"  # Change this!
    email: user@homeserver.local
    groups:
      - users

# To generate password hashes:
# 1. Run: docker run --rm authelia/authelia:latest authelia hash-password 'your_password_here'
# 2. Copy the generated hash to replace the placeholder above
# 3. Restart Authelia service to apply changes
#
# Example hash generation:
# $ docker run --rm authelia/authelia:latest authelia hash-password 'mypassword123'
# Password hash: $argon2id$v=19$m=65536,t=3,p=4$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t1MF//X6yA

# Security Notes:
# - Change all default passwords before deployment
# - Use strong passwords (minimum 12 characters with mixed case, numbers, symbols)
# - Consider using a password manager for password generation
# - Regularly rotate passwords for service accounts
# - Enable 2FA for all admin accounts