services:
  github-runner:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    networks:
      - frontend
    environment:
      # Let the container auto-generate unique names (RUNNER_NAME not set)
      - RUNNER_WORKDIR=/tmp/runner/work
      - RUNNER_GROUP=${RUNNER_GROUP}
      - RUNNER_SCOPE=repo
      - LABELS=self-hosted,Linux,X64,homeserver,docker
      - REPO_URL=https://github.com/${GITHUB_REPOSITORY}
      - ACCESS_TOKEN=${GITHUB_RUNNER_TOKEN}
      - RUNNER_REPLACE_EXISTING=false
      - DISABLE_RUNNER_UPDATE=false
      - EPHEMERAL=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_DOCKER_SERVICE=false
      - RUN_AS_ROOT=true
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/runner/work:/tmp/runner/work
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PROJECT_PATH}:/workspace:ro
      - /usr/bin/docker:/usr/bin/docker:ro
    mem_limit: ${RUNNER_MEMORY_LIMIT}
    cpus: ${RUNNER_CPU_LIMIT}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "com.github.runner.scaler=worker"

