services:
  github-runner:
    image: myoung34/github-runner:2.311.0-ubuntu-22.04
    container_name: github-runner
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_WORKDIR=/tmp/runner/work
      - RUNNER_GROUP=${RUNNER_GROUP}
      - RUNNER_SCOPE=repo
      - LABELS=self-hosted,Linux,X64,homeserver,docker
      - REPO_URL=https://github.com/${GITHUB_REPOSITORY}
      - ACCESS_TOKEN=${GITHUB_RUNNER_TOKEN}
      - RUNNER_REPLACE_EXISTING=false
      - DISABLE_RUNNER_UPDATE=false
      - EPHEMERAL=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_DOCKER_SERVICE=false
      - RUNNER_ALLOW_RUNASROOT=1
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/runner/work:/tmp/runner/work
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PROJECT_PATH}:/workspace:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
    mem_limit: ${RUNNER_MEMORY_LIMIT}
    cpus: ${RUNNER_CPU_LIMIT}
    security_opt:
      - no-new-privileges:true
    user: "${PUID}:${PGID}"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

