global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'null'

receivers:
- name: 'null'
  # No notification channels configured - alerts are logged only
  # Add email_configs, webhook_configs, or other receivers as needed

inhibit_rules: []