services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ../../configs/fail2ban:/etc/fail2ban:ro
      - ${SSD_PATH}/monitoring/fail2ban:/var/lib/fail2ban
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - TZ=${TZ}
      - F2B_LOG_LEVEL=INFO
      - F2B_LOG_TARGET=/var/log/fail2ban.log
      - F2B_DB_PURGE_AGE=1d
    mem_limit: 256m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true