title: Romulus Homelab
favicon: https://romulus.hu/favicon.ico
theme: dark
color: slate
headerStyle: clean
hideVersion: true

layout:
  Media:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 3
  AI:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 5
  Monitoring:
    style: row
    columns: 3
  Utilities:
    style: row
    columns: 1
  Notifications:
    style: row
    columns: 1
