groups:
- name: working_infrastructure_alerts
  rules:
  - alert: ServiceDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
      category: infrastructure
    annotations:
      summary: "Service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} has been down for more than 2 minutes."

  - alert: HighSystemLoad
    expr: node_load1 > 10
    for: 3m
    labels:
      severity: warning
      category: performance
    annotations:
      summary: "High system load on {{ $labels.instance }}"
      description: "System load is {{ $value }} (1m average)"

  - alert: CriticalSystemLoad  
    expr: node_load1 > 15
    for: 1m
    labels:
      severity: critical
      category: performance
    annotations:
      summary: "Critical system load on {{ $labels.instance }}"
      description: "System load is {{ $value }} (1m average) - immediate attention required"

- name: working_container_alerts
  rules:
  - alert: HighContainerCPU
    expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
      category: containers
    annotations:
      summary: "High CPU usage in container {{ $labels.name }}"
      description: "Container {{ $labels.name }} CPU usage is {{ $value }}%"

  - alert: CriticalContainerCPU
    expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 95
    for: 2m
    labels:
      severity: critical
      category: containers
    annotations:
      summary: "Critical CPU usage in container {{ $labels.name }}"
      description: "Container {{ $labels.name }} CPU usage is {{ $value }}%"

  - alert: HighContainerMemory
    expr: container_memory_usage_bytes{name!=""} / 1024 / 1024 > 1000
    for: 5m
    labels:
      severity: warning
      category: containers
    annotations:
      summary: "High memory usage in container {{ $labels.name }}"
      description: "Container {{ $labels.name }} memory usage is {{ $value }}MB"

- name: working_application_alerts  
  rules:
  - alert: QBittorrentDisconnected
    expr: qbittorrent_connected == 0
    for: 5m
    labels:
      severity: warning
      category: applications
    annotations:
      summary: "qBittorrent is disconnected"
      description: "qBittorrent has been disconnected for more than 5 minutes"

  - alert: QBittorrentDown
    expr: qbittorrent_up == 0  
    for: 2m
    labels:
      severity: critical
      category: applications
    annotations:
      summary: "qBittorrent service is down"
      description: "qBittorrent exporter cannot reach the service"

- name: working_network_alerts
  rules:
  - alert: WebsiteDown
    expr: probe_success{job="blackbox-http"} == 0
    for: 2m
    labels:
      severity: critical
      category: network
    annotations:
      summary: "Website {{ $labels.instance }} is down"
      description: "HTTP probe failed for {{ $labels.instance }}"

  - alert: PingFailed
    expr: probe_success{job="blackbox-icmp"} == 0
    for: 2m  
    labels:
      severity: critical
      category: network
    annotations:
      summary: "Ping failed to {{ $labels.instance }}"
      description: "ICMP probe failed for {{ $labels.instance }}"