services:
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    restart: unless-stopped
    user: "65534:65534"
    networks:
      - monitoring
      - frontend
    ports:
      - "${ALERTMANAGER_PORT:-9093}:9093"
    volumes:
      - ${SSD_PATH}/actions-runner/_work/romulus/romulus/configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ${SSD_PATH}/monitoring/alertmanager:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://alerts.${DOMAIN}'
      - '--web.route-prefix=/'
      - '--cluster.listen-address='
      - '--log.level=info'
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    mem_limit: 512m
    cpus: 1
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3