# Generated .env file from Vault secrets
# This file is automatically generated by Vault Agent
# Do not edit manually - changes will be overwritten

# Basic Configuration
TZ={{ with secret "kv/homeserver/config" }}{{ .Data.data.TZ }}{{ end }}
PUID={{ with secret "kv/homeserver/config" }}{{ .Data.data.PUID }}{{ end }}
PGID={{ with secret "kv/homeserver/config" }}{{ .Data.data.PGID }}{{ end }}

# Domain Configuration
DOMAIN={{ with secret "kv/homeserver/config" }}{{ .Data.data.DOMAIN }}{{ end }}

# Storage Paths
NVME_PATH={{ with secret "kv/homeserver/config" }}{{ .Data.data.NVME_PATH }}{{ end }}
SSD_PATH={{ with secret "kv/homeserver/config" }}{{ .Data.data.SSD_PATH }}{{ end }}
HDD_PATH={{ with secret "kv/homeserver/config" }}{{ .Data.data.HDD_PATH }}{{ end }}

# Cloudflare Secrets
CLOUDFLARE_API_TOKEN={{ with secret "kv/homeserver/cloudflare" }}{{ .Data.data.api_token }}{{ end }}
CLOUDFLARE_ZONE_ID={{ with secret "kv/homeserver/cloudflare" }}{{ .Data.data.zone_id }}{{ end }}
CLOUDFLARE_EMAIL={{ with secret "kv/homeserver/cloudflare" }}{{ .Data.data.email }}{{ end }}

# Database Secrets
MYSQL_ROOT_PASSWORD={{ with secret "kv/homeserver/database" }}{{ .Data.data.mysql_root_password }}{{ end }}
REDIS_PASSWORD={{ with secret "kv/homeserver/database" }}{{ .Data.data.redis_password }}{{ end }}
MONITORING_DB_PASSWORD={{ with secret "kv/homeserver/database" }}{{ .Data.data.monitoring_password }}{{ end }}
BACKUP_DB_PASSWORD={{ with secret "kv/homeserver/database" }}{{ .Data.data.backup_password }}{{ end }}

# Service Authentication
GF_SECURITY_ADMIN_PASSWORD={{ with secret "kv/homeserver/services" }}{{ .Data.data.grafana_password }}{{ end }}
QBITTORRENT_PASSWORD={{ with secret "kv/homeserver/services" }}{{ .Data.data.qbittorrent_password }}{{ end }}
PLEX_CLAIM={{ with secret "kv/homeserver/services" }}{{ .Data.data.plex_claim }}{{ end }}

# Authelia Secrets
AUTHELIA_JWT_SECRET={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.jwt_secret }}{{ end }}
AUTHELIA_SESSION_SECRET={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.session_secret }}{{ end }}
AUTHELIA_STORAGE_ENCRYPTION_KEY={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.storage_key }}{{ end }}

# Authelia User Credentials
AUTHELIA_ADMIN_PASSWORD_HASH={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.admin_password_hash }}{{ end }}
AUTHELIA_ADMIN_EMAIL={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.admin_email }}{{ end }}
AUTHELIA_MONITORING_PASSWORD_HASH={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.monitoring_password_hash }}{{ end }}
AUTHELIA_MONITORING_EMAIL={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.monitoring_email }}{{ end }}
AUTHELIA_USER1_PASSWORD_HASH={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.user1_password_hash }}{{ end }}
AUTHELIA_USER1_EMAIL={{ with secret "kv/homeserver/authelia" }}{{ .Data.data.user1_email }}{{ end }}

# NTP Server
NTP_SERVER={{ with secret "kv/homeserver/config" }}{{ .Data.data.NTP_SERVER }}{{ end }}

# Gaming Services
CS2_SERVER_NAME={{ with secret "kv/homeserver/gaming" }}{{ .Data.data.cs2_server_name }}{{ end }}
CS2_RCON_PASSWORD={{ with secret "kv/homeserver/gaming" }}{{ .Data.data.cs2_rcon_password }}{{ end }}
CS2_SERVER_PASSWORD={{ with secret "kv/homeserver/gaming" }}{{ .Data.data.cs2_server_password }}{{ end }}
STEAM_TOKEN={{ with secret "kv/homeserver/gaming" }}{{ .Data.data.steam_token }}{{ end }}
TS3_SERVER_ADMIN_PASSWORD={{ with secret "kv/homeserver/gaming" }}{{ .Data.data.ts3_admin_password }}{{ end }}

# Notification Settings
DISCORD_WEBHOOK_URL={{ with secret "kv/homeserver/notifications" }}{{ .Data.data.discord_webhook }}{{ end }}

# Backup Configuration
BACKUP_ENCRYPTION_KEY={{ with secret "kv/homeserver/backup" }}{{ .Data.data.encryption_key }}{{ end }}
B2_ACCOUNT_ID={{ with secret "kv/homeserver/backup" }}{{ .Data.data.b2_account_id }}{{ end }}
B2_ACCOUNT_KEY={{ with secret "kv/homeserver/backup" }}{{ .Data.data.b2_account_key }}{{ end }}
B2_BUCKET_NAME={{ with secret "kv/homeserver/backup" }}{{ .Data.data.b2_bucket_name }}{{ end }}

# GitHub Actions Runner
GITHUB_REPOSITORY={{ with secret "kv/homeserver/github" }}{{ .Data.data.repository }}{{ end }}
GITHUB_RUNNER_TOKEN={{ with secret "kv/homeserver/github" }}{{ .Data.data.runner_token }}{{ end }}
RUNNER_NAME={{ with secret "kv/homeserver/config" }}{{ .Data.data.RUNNER_NAME }}{{ end }}

# Port Configurations
PLEX_PORT=32400
QBITTORRENT_PORT=8080
GRAFANA_PORT=3000
PROMETHEUS_PORT=9090
TEAMSPEAK_VOICE_PORT=9987
TEAMSPEAK_QUERY_PORT=10011
TEAMSPEAK_FILES_PORT=30033
CS2_PORT=27015
CS2_RCON_PORT=27025

# Resource Limits
PLEX_MEMORY_LIMIT=8g
PLEX_CPU_LIMIT=6
CS2_MEMORY_LIMIT=4g
CS2_CPU_LIMIT=4
MARIADB_MEMORY_LIMIT=2g
REDIS_MEMORY_LIMIT=256m

# Runtime Configuration
LOG_LEVEL=info
BACKUP_SCHEDULE="0 2 * * *"
UPDATE_CHECK_SCHEDULE="0 6 * * 0"
RUNNER_GROUP=default
RUNNER_EPHEMERAL=false
RUNNER_MEMORY_LIMIT=2g
RUNNER_MEMORY_RESERVATION=1g
RUNNER_CPU_LIMIT=2.0
PROJECT_PATH={{ with secret "kv/homeserver/config" }}{{ .Data.data.PROJECT_PATH }}{{ end }}
DEVELOPMENT_MODE=false
DEBUG_LOGGING=false